@startuml
!theme plain
skinparam roundcorner 0
skinparam activity {
  BackgroundColor lightblue
  BorderColor darkblue
  ArrowColor black
}

start
:Sub-proceso 1: Construir Conjunto de Caracteres; <<procedure>>

:Inicializar **conjunto_total** vacío;

if (¿Mayúsculas == 's'?) then (Sí)
  :Añadir alfabeto en mayúsculas a **conjunto_total**;
else (No)
endif

if (¿Minúsculas == 's'?) then (Sí)
  :Añadir alfabeto en minúsculas a **conjunto_total**;
else (No)
endif

if (¿Números == 's'?) then (Sí)
  :Añadir dígitos a **conjunto_total**;
else (No)
endif

if (¿Símbolos == 's'?) then (Sí)
  :Añadir símbolos especiales a **conjunto_total**;
else (No)
endif

stop
@enduml
