@startuml
!theme plain
skinparam roundcorner 0
skinparam activity {
  BackgroundColor lightblue
  BorderColor darkblue
  ArrowColor black
}

start
:Sub-proceso 2: Generar y Mostrar Contraseña; <<procedure>>

:Inicializar **password_final** vacía;

while (¿Tamaño de **password_final** < **longitud**?) is (Sí)
  :Extraer 1 carácter al azar de **conjunto_total**;
  :Añadir a **password_final**;
endwhile (No)

:Mostrar **password_final** en pantalla; <<output>>

stop
@enduml
